### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by rafalradomski** [justinmahar/react-ig-embed#1]
Hi, I just tried to use your lib with create react app, and I got an error:

`./node_modules/react-ig-embed/dist/components/IGEmbed.js 91:22
Module parse failed: Unexpected token (91:22)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     if (win && processTime >= 0) {
|       // This call will use the IG embed script to process all elements with the `instagram-media` class name.
>       if (win.instgrm?.Embeds) {
|         // console.log('Processing...', Date.now());
|         win.instgrm.Embeds.process();`

![error](https://user-images.githubusercontent.com/8066536/152705767-ea9c3189-5d6f-4db2-a06a-efff476c9dee.png)

Any ideas how to fix that?

**Comment by justinmahar** [comment]
It looks it's complaining about the optional chaining `?.` syntax. Let me see if there's something I can do on a compilation level.

**Comment by justinmahar** [comment]
Found this thread: https://github.com/webpack/webpack/issues/10227

Possible solution:

> To resolve this issue for legacy builds that use webpack v4, add @babel/plugin-proposal-optional-chaining to your babel plugins

> ### For Babel
> Add `@babel/plugin-proposal-optional-chaining` and `@babel/plugin-proposal-nullish-coalescing-operator` plugins in your config
> 
> ### For Typescript
> Do not upgrade to version 3.8 or set compiler option `target` to `es2019`
> 
> ### Yarn/NPM level
> See the [#10227 (comment)](https://github.com/webpack/webpack/issues/10227#issuecomment-698662228)

**Comment by justinmahar** [comment]
Weird that create react app can't handle `?.` syntax, which was standardized in ES2020.

**Comment by justinmahar** [comment]
Alright, I removed the `?.` optional chaining syntax and am now just checking it the good old fashioned way.

Try running:

```
npm i react-ig-embed@latest
```

And see if that fixes your issue.

**Comment by rafalradomski** [comment]
Thank you for the quick response @justinmahar, now the lib works, but I getting a new error:
"Instagram embed script not found. Unable to process Instagram embed"

![loader](https://user-images.githubusercontent.com/8066536/152749187-d675ed11-ecec-417b-ab3e-b00a5b341d23.png)

I followed the readme and used:
```
import { IGEmbed } from 'react-ig-embed';
<IGEmbed url="https://www.instagram.com/p/CUbHfhpswxt/" />
```

Do I need to add something extra?

**Comment by justinmahar** [comment]
You're welcome!

Can you share your `package.json`? It seems like it's not loading Instagram's Embed JS script. This should happen automatically in the IGEmbed component, but you can manually import it with:

```
<script src="//www.instagram.com/embed.js"></script>
```

But I'm wondering if there's a dependency version issue with this. This project depends on React 17.

**Comment by justinmahar** [comment]
If you're using an old version of `react-scripts` (here's the [CHANGELOG](https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md)), you can try [updating](https://create-react-app.dev/docs/updating-to-new-releases/#:~:text=To%20update%20an%20existing%20project,react%2Dscripts%20version%20in%20package.) and see if that fixes it.

**Comment by justinmahar** [comment]
@rafalradomski I believe I've fixed the issue you were seeing!

I refactored the project a bit to simplify things, and I created a react app using create react app. I now have a live demo of the component working in create react app:

- [Live Demo](https://justinmahar.github.io/react-ig-embed-demo/)
- [Demo project source code](https://github.com/justinmahar/react-ig-embed-demo)

You can see [exactly how I'm using the component here](https://github.com/justinmahar/react-ig-embed-demo/blob/master/src/App.js).

Try running:

```
npm i react-ig-embed@latest
```

And see if it works now.

**Comment by rafalradomski** [comment]
Hi @justinmahar thank you a lot, now works like a charm, great work, you saved my day!

**Comment by justinmahar** [comment]
Hey @rafalradomski! Just wanted to give you a heads up that I've deprecated this project and moved the instagram embedder to a new project: https://www.npmjs.com/package/react-social-media-embed

You might want to switch over to that one, I've refactored the Instagram embedder quite a bit.
